-- =============================================================================
-- CWS — phpMyAdmin live update order (plan2)
-- =============================================================================
--
-- Run on database `cws_cms` IN ORDER:
--
--   1) 01_schema_pending_migrations.sql
--      → Columns/tables from migrations 003–016 if missing.
--      → Ignore "Duplicate column name" if already applied.
--
--   2) 02_fix_menu_db_keys.sql
--      → footer_services / footer_products menu keys.
--
--   ★ 3) 07_plan2_homepage_full_update.sql  (RECOMMENDED)
--      → Plan2 homepage: 13 sections, new order, full JSON payloads.
--      → Does NOT touch blog, services, menus, or other pages.
--
--   ★ 4) 08_plan2_site_settings_promo.sql
--      → Top announcement / promo bar (admin-editable fields).
--
--   (Optional legacy) 05_homepage_ONLY_full_update.sql — same content as 07 if regenerated
--
--   OR section-by-section: database/live/homepage-sections/
--      00_page_setup.sql → 00_hero_slider.sql … 12_cta.sql
--
-- Regenerate from code:
--   node frontend/scripts/export-homepage-live-sql.mjs
--
-- Local WAMP apply:
--   node database/scripts/apply-local.mjs
--
-- NOT in this bundle (future plan2 phases — use existing admin):
--   /case-studies/[slug], /industries/[slug], /technologies/[slug] routes
--   Video testimonials CMS module, dedicated cost-calculator table
--   Full awards/certifications/logo library tables
--
-- =============================================================================

SELECT 'Run 01 → 02 → 07 → 08 on production' AS info;
