-- Homepage ONLY - run after 00_page_setup.sql
USE cws_cms;
SET NAMES utf8mb4;
SET @page_id := (SELECT id FROM pages WHERE is_homepage = 1 LIMIT 1);
SET @page_id := IFNULL(@page_id, (SELECT id FROM pages WHERE slug = 'home' LIMIT 1));

SET NAMES utf8mb4;
-- Section: hero_slider
UPDATE homepage_sections
SET sort_order = 0, layout = 'hero_slider', status = 'published',
    admin_title = 'Hero',
    payload = '{"acfFcLayout":"hero_slider","eyebrow":"Global Web - Mobile - Digital Marketing Agency","headline":"Turn visitors into paying customers","subheadline":"Creative Web Solutions designs, builds, and markets high-performing websites and apps for brands that sell worldwide - one team from first sketch to measurable growth.","headlineParts":[{"text":"paying","tone":"green"},{"text":"customers","tone":"blue"}],"ctaPrimary":{"label":"Get free proposal","href":"#ask-price"},"ctaSecondary":{"label":"See our work","href":"/portfolio"},"slides":[{"image":{"url":"/assets/images/hero1.png"}},{"image":{"url":"/assets/images/hero2.png"}},{"image":{"url":"/assets/images/hero3.png"}}],"heroVisual":"svg","personImage":"/assets/images/hero2.png","personImageAlt":"Creative Web Solutions - website and mobile product team","stats":[{"icon":"fas fa-project-diagram","count":549,"label":"Projects shipped","tone":"blue"},{"icon":"fas fa-users","count":320,"label":"Clients worldwide","tone":"green"},{"icon":"fas fa-award","count":15,"label":"Years crafting digital","tone":"royal"}],"gmbRating":4.9,"gmbReviewCount":"120+","gmbReviews":[{"author":"Amit K.","rating":5,"text":"Lightning-fast site, premium feel. Our enquiry form finally gets used every day.","ago":"3 weeks ago"},{"author":"Priya Sharma","rating":5,"text":"SEO and paid campaigns are aligned - we see which pages actually drive leads.","ago":"1 month ago"},{"author":"Vikram S.","rating":5,"text":"Ecommerce launch was smooth. Checkout, payments, and handover were pro end-to-end.","ago":"2 months ago"}],"marqueeItems":[{"letter":"W","title":"Website development","href":"/website-development-zirakpur"},{"letter":"M","title":"Mobile apps","href":"/mobile-app-development-zirakpur"},{"letter":"S","title":"SEO & growth","href":"/seo-services-zirakpur"},{"letter":"A","title":"Digital marketing","href":"/digital-marketing-zirakpur"},{"letter":"U","title":"UI/UX design","href":"/ui-ux-design-zirakpur"},{"letter":"E","title":"Ecommerce","href":"/ecommerce-website-zirakpur"}]}'
WHERE page_id = @page_id AND layout = 'hero_slider' AND status <> 'trash';

INSERT INTO homepage_sections (page_id, sort_order, layout, status, admin_title, payload)
SELECT @page_id, 0, 'hero_slider', 'published', 'Hero', '{"acfFcLayout":"hero_slider","eyebrow":"Global Web - Mobile - Digital Marketing Agency","headline":"Turn visitors into paying customers","subheadline":"Creative Web Solutions designs, builds, and markets high-performing websites and apps for brands that sell worldwide - one team from first sketch to measurable growth.","headlineParts":[{"text":"paying","tone":"green"},{"text":"customers","tone":"blue"}],"ctaPrimary":{"label":"Get free proposal","href":"#ask-price"},"ctaSecondary":{"label":"See our work","href":"/portfolio"},"slides":[{"image":{"url":"/assets/images/hero1.png"}},{"image":{"url":"/assets/images/hero2.png"}},{"image":{"url":"/assets/images/hero3.png"}}],"heroVisual":"svg","personImage":"/assets/images/hero2.png","personImageAlt":"Creative Web Solutions - website and mobile product team","stats":[{"icon":"fas fa-project-diagram","count":549,"label":"Projects shipped","tone":"blue"},{"icon":"fas fa-users","count":320,"label":"Clients worldwide","tone":"green"},{"icon":"fas fa-award","count":15,"label":"Years crafting digital","tone":"royal"}],"gmbRating":4.9,"gmbReviewCount":"120+","gmbReviews":[{"author":"Amit K.","rating":5,"text":"Lightning-fast site, premium feel. Our enquiry form finally gets used every day.","ago":"3 weeks ago"},{"author":"Priya Sharma","rating":5,"text":"SEO and paid campaigns are aligned - we see which pages actually drive leads.","ago":"1 month ago"},{"author":"Vikram S.","rating":5,"text":"Ecommerce launch was smooth. Checkout, payments, and handover were pro end-to-end.","ago":"2 months ago"}],"marqueeItems":[{"letter":"W","title":"Website development","href":"/website-development-zirakpur"},{"letter":"M","title":"Mobile apps","href":"/mobile-app-development-zirakpur"},{"letter":"S","title":"SEO & growth","href":"/seo-services-zirakpur"},{"letter":"A","title":"Digital marketing","href":"/digital-marketing-zirakpur"},{"letter":"U","title":"UI/UX design","href":"/ui-ux-design-zirakpur"},{"letter":"E","title":"Ecommerce","href":"/ecommerce-website-zirakpur"}]}'
FROM DUAL
WHERE @page_id IS NOT NULL
  AND NOT EXISTS (
    SELECT 1 FROM homepage_sections hs
    WHERE hs.page_id = @page_id AND hs.layout = 'hero_slider' AND hs.status <> 'trash'
  );
