-- Homepage ONLY - run after 00_page_setup.sql
USE cws_cms;
SET NAMES utf8mb4;
SET @page_id := (SELECT id FROM pages WHERE is_homepage = 1 LIMIT 1);
SET @page_id := IFNULL(@page_id, (SELECT id FROM pages WHERE slug = 'home' LIMIT 1));

-- Section: hero_slider
UPDATE homepage_sections
SET sort_order = 0, layout = 'hero_slider', status = 'published',
    admin_title = 'Hero',
    payload = '{"acfFcLayout":"hero_slider","eyebrow":"Premium Software & Digital Agency","headline":"Transform ideas into scalable digital products","subheadline":"Web development, mobile apps, AI integrations, and growth marketing for brands that compete globally - one accountable team from discovery to launch.","headlineParts":[{"text":"scalable","tone":"green"},{"text":"digital products","tone":"blue"}],"ctaPrimary":{"label":"Book consultation","href":"#ask-price"},"ctaSecondary":{"label":"Get free proposal","href":"/contact#contact-form"},"slides":[{"image":{"url":"/assets/images/hero1.png"}},{"image":{"url":"/assets/images/hero2.png"}},{"image":{"url":"/assets/images/hero3.png"}}],"heroVisual":"svg","personImage":"/assets/images/hero2.png","personImageAlt":"Creative Web Solutions - product engineering team","stats":[{"icon":"fas fa-project-diagram","count":549,"label":"Projects delivered","tone":"blue"},{"icon":"fas fa-users","count":320,"label":"Happy clients","tone":"green"},{"icon":"fas fa-globe-americas","count":25,"label":"Countries served","tone":"royal"},{"icon":"fas fa-award","count":15,"label":"Years experience","tone":"orange"}],"gmbRating":4.9,"gmbReviewCount":"120+","gmbReviews":[{"author":"Amit K.","rating":5,"text":"Enterprise-grade delivery with clear milestones. Our platform launch stayed on scope and on time.","ago":"3 weeks ago"},{"author":"Priya Sharma","rating":5,"text":"SEO, paid media, and product UX finally align - we attribute revenue to channels, not guesses.","ago":"1 month ago"},{"author":"Vikram S.","rating":5,"text":"Mobile app plus admin dashboard shipped in sprints. Communication felt like an in-house product team.","ago":"2 months ago"}],"marqueeItems":[{"letter":"W","title":"Website development","href":"/website-development-zirakpur"},{"letter":"M","title":"Mobile apps","href":"/mobile-app-development-zirakpur"},{"letter":"A","title":"AI solutions","href":"/custom-software-development-zirakpur"},{"letter":"S","title":"SEO & growth","href":"/seo-services-zirakpur"},{"letter":"U","title":"UI/UX design","href":"/ui-ux-design-zirakpur"},{"letter":"E","title":"Ecommerce","href":"/ecommerce-website-zirakpur"}]}'
WHERE page_id = @page_id AND layout = 'hero_slider' AND status <> 'trash';

INSERT INTO homepage_sections (page_id, sort_order, layout, status, admin_title, payload)
SELECT @page_id, 0, 'hero_slider', 'published', 'Hero', '{"acfFcLayout":"hero_slider","eyebrow":"Premium Software & Digital Agency","headline":"Transform ideas into scalable digital products","subheadline":"Web development, mobile apps, AI integrations, and growth marketing for brands that compete globally - one accountable team from discovery to launch.","headlineParts":[{"text":"scalable","tone":"green"},{"text":"digital products","tone":"blue"}],"ctaPrimary":{"label":"Book consultation","href":"#ask-price"},"ctaSecondary":{"label":"Get free proposal","href":"/contact#contact-form"},"slides":[{"image":{"url":"/assets/images/hero1.png"}},{"image":{"url":"/assets/images/hero2.png"}},{"image":{"url":"/assets/images/hero3.png"}}],"heroVisual":"svg","personImage":"/assets/images/hero2.png","personImageAlt":"Creative Web Solutions - product engineering team","stats":[{"icon":"fas fa-project-diagram","count":549,"label":"Projects delivered","tone":"blue"},{"icon":"fas fa-users","count":320,"label":"Happy clients","tone":"green"},{"icon":"fas fa-globe-americas","count":25,"label":"Countries served","tone":"royal"},{"icon":"fas fa-award","count":15,"label":"Years experience","tone":"orange"}],"gmbRating":4.9,"gmbReviewCount":"120+","gmbReviews":[{"author":"Amit K.","rating":5,"text":"Enterprise-grade delivery with clear milestones. Our platform launch stayed on scope and on time.","ago":"3 weeks ago"},{"author":"Priya Sharma","rating":5,"text":"SEO, paid media, and product UX finally align - we attribute revenue to channels, not guesses.","ago":"1 month ago"},{"author":"Vikram S.","rating":5,"text":"Mobile app plus admin dashboard shipped in sprints. Communication felt like an in-house product team.","ago":"2 months ago"}],"marqueeItems":[{"letter":"W","title":"Website development","href":"/website-development-zirakpur"},{"letter":"M","title":"Mobile apps","href":"/mobile-app-development-zirakpur"},{"letter":"A","title":"AI solutions","href":"/custom-software-development-zirakpur"},{"letter":"S","title":"SEO & growth","href":"/seo-services-zirakpur"},{"letter":"U","title":"UI/UX design","href":"/ui-ux-design-zirakpur"},{"letter":"E","title":"Ecommerce","href":"/ecommerce-website-zirakpur"}]}'
FROM DUAL
WHERE @page_id IS NOT NULL
  AND NOT EXISTS (
    SELECT 1 FROM homepage_sections hs
    WHERE hs.page_id = @page_id AND hs.layout = 'hero_slider' AND hs.status <> 'trash'
  );
