-- Homepage ONLY - run after 00_page_setup.sql
USE cws_cms;
SET NAMES utf8mb4;
SET @page_id := (SELECT id FROM pages WHERE is_homepage = 1 LIMIT 1);
SET @page_id := IFNULL(@page_id, (SELECT id FROM pages WHERE slug = 'home' LIMIT 1));

-- Section: services_grid
UPDATE homepage_sections
SET sort_order = 3, layout = 'services_grid', status = 'published',
    admin_title = 'Services',
    payload = '{"acfFcLayout":"services_grid","sectionTheme":"dark","badge":"Services","title":"Full-stack capabilities for $5k-$100k+ engagements","subtitle":"Strategy, design, engineering, and growth in one partner - each service links to a dedicated SEO landing page.","items":[{"icon":"fas fa-paint-brush","image":"https://images.unsplash.com/photo-1561070791-2526d30994b5?auto=format&fit=crop&w=960&h=540&q=85","title":"Web design","desc":"Bold, on-brand interfaces that guide visitors to action - desktop and mobile, built for trust at first scroll.","href":"/ui-ux-design-zirakpur","tone":"pink"},{"icon":"fas fa-code","image":"https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=960&h=540&q=85","title":"Website development","desc":"Fast, secure sites and landing pages with forms, CRM hooks, and analytics baked in - code your team can extend.","href":"/website-development-zirakpur","tone":"blue"},{"icon":"fas fa-mobile-alt","image":"https://images.unsplash.com/photo-1512945903694-92d7a22944f4?auto=format&fit=crop&w=960&h=540&q=85","title":"Mobile apps","desc":"Polished Android & iOS experiences users keep - onboarding, push, payments, and admin when you need scale.","href":"/mobile-app-development-zirakpur","tone":"green"},{"icon":"fas fa-bullhorn","image":"https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=960&h=540&q=85","title":"Digital marketing","desc":"Google Ads, Meta, and landing pages engineered for leads - weekly clarity on cost per enquiry, not vanity charts.","href":"/digital-marketing-zirakpur","tone":"orange"},{"icon":"fas fa-robot","image":"https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=960&h=540&q=85","title":"Custom software & AI","desc":"Dashboards, portals, automation, and AI features that replace manual work - shaped around how your team operates.","href":"/custom-software-development-zirakpur","tone":"grey"},{"icon":"fas fa-pen-nib","image":"https://images.unsplash.com/photo-1626785774573-4b7999ee4feb?auto=format&fit=crop&w=960&h=540&q=85","title":"Brand & graphics","desc":"Logos, decks, ad kits, and social systems that look expensive everywhere - consistent, launch-ready creative.","href":"/graphic-designing-zirakpur","tone":"pink"},{"icon":"fas fa-cart-shopping","image":"https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=960&h=540&q=85","title":"Ecommerce","desc":"Shopify, WooCommerce, or custom storefronts with checkout that feels effortless - merchandising built to convert.","href":"/ecommerce-website-zirakpur","tone":"green"},{"icon":"fas fa-chart-line","image":"https://images.unsplash.com/photo-1432888498266-38ffec3eaf4a?auto=format&fit=crop&w=960&h=540&q=85","title":"SEO & content","desc":"Technical SEO, topic clusters, and content that ranks - so the right buyers find you when intent is highest.","href":"/seo-services-zirakpur","tone":"blue"}]}'
WHERE page_id = @page_id AND layout = 'services_grid' AND status <> 'trash';

INSERT INTO homepage_sections (page_id, sort_order, layout, status, admin_title, payload)
SELECT @page_id, 3, 'services_grid', 'published', 'Services', '{"acfFcLayout":"services_grid","sectionTheme":"dark","badge":"Services","title":"Full-stack capabilities for $5k-$100k+ engagements","subtitle":"Strategy, design, engineering, and growth in one partner - each service links to a dedicated SEO landing page.","items":[{"icon":"fas fa-paint-brush","image":"https://images.unsplash.com/photo-1561070791-2526d30994b5?auto=format&fit=crop&w=960&h=540&q=85","title":"Web design","desc":"Bold, on-brand interfaces that guide visitors to action - desktop and mobile, built for trust at first scroll.","href":"/ui-ux-design-zirakpur","tone":"pink"},{"icon":"fas fa-code","image":"https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=960&h=540&q=85","title":"Website development","desc":"Fast, secure sites and landing pages with forms, CRM hooks, and analytics baked in - code your team can extend.","href":"/website-development-zirakpur","tone":"blue"},{"icon":"fas fa-mobile-alt","image":"https://images.unsplash.com/photo-1512945903694-92d7a22944f4?auto=format&fit=crop&w=960&h=540&q=85","title":"Mobile apps","desc":"Polished Android & iOS experiences users keep - onboarding, push, payments, and admin when you need scale.","href":"/mobile-app-development-zirakpur","tone":"green"},{"icon":"fas fa-bullhorn","image":"https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=960&h=540&q=85","title":"Digital marketing","desc":"Google Ads, Meta, and landing pages engineered for leads - weekly clarity on cost per enquiry, not vanity charts.","href":"/digital-marketing-zirakpur","tone":"orange"},{"icon":"fas fa-robot","image":"https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=960&h=540&q=85","title":"Custom software & AI","desc":"Dashboards, portals, automation, and AI features that replace manual work - shaped around how your team operates.","href":"/custom-software-development-zirakpur","tone":"grey"},{"icon":"fas fa-pen-nib","image":"https://images.unsplash.com/photo-1626785774573-4b7999ee4feb?auto=format&fit=crop&w=960&h=540&q=85","title":"Brand & graphics","desc":"Logos, decks, ad kits, and social systems that look expensive everywhere - consistent, launch-ready creative.","href":"/graphic-designing-zirakpur","tone":"pink"},{"icon":"fas fa-cart-shopping","image":"https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=960&h=540&q=85","title":"Ecommerce","desc":"Shopify, WooCommerce, or custom storefronts with checkout that feels effortless - merchandising built to convert.","href":"/ecommerce-website-zirakpur","tone":"green"},{"icon":"fas fa-chart-line","image":"https://images.unsplash.com/photo-1432888498266-38ffec3eaf4a?auto=format&fit=crop&w=960&h=540&q=85","title":"SEO & content","desc":"Technical SEO, topic clusters, and content that ranks - so the right buyers find you when intent is highest.","href":"/seo-services-zirakpur","tone":"blue"}]}'
FROM DUAL
WHERE @page_id IS NOT NULL
  AND NOT EXISTS (
    SELECT 1 FROM homepage_sections hs
    WHERE hs.page_id = @page_id AND hs.layout = 'services_grid' AND hs.status <> 'trash'
  );
